### ISSUE TITLE
REQUEST: asdf-amberframework?

### ISSUE THREAD

**Issue by zenny** [asdf-community/asdf-crystal#13]
Hi,

Thanks for creating a crystal plugin for asdf.

It would be wonderful to have an asdf-plugin to install amberframework.org instead of going through steps (though not many) at (https://amberframework.gitbook.io/amber/getting-started/quick-start).

It pops up an error with default method specified above as stated in https://github.com/amberframework/amber/issues/807, fyi.

Cheers,
/z

**Comment by robacarp** [comment]
Amber projects should use the amber binary located in the project bin directory, not any amber command installed in the system, so I think it will be misleading to have an Amber version manager.

**Comment by imbsky** [comment]
We already have several options.
https://docs.amberframework.org/amber/getting-started
