### ISSUE TITLE
Binary output on macOS 10.13.6 on attempt to install

### ISSUE THREAD

**Issue by kumekay** [asdf-community/asdf-crystal#16]
When I'm trying to install crystal (any version), I receive binary output to the console

![image](https://user-images.githubusercontent.com/2738/43798537-2e03b84c-9a8b-11e8-8062-2ded29a09b83.png)

Env:
asdf version: v0.5.1
commit 6e9da8a

asdf-crystal (latest master) commit c14e8b330f07a52baf3d43e72cc8cc1456a78b36

**Comment by imbsky** [comment]
Does this still happen? I couldn't check it in my environment.

**Comment by kumekay** [comment]
I've checked wit asdf 0.7.6 and plugin eee67fd
It works just fine with recent versions  (like 0.32.1)of crystal, 
with older versions of crystal it also works, but I see warning in the  output

```
/var/folders/2p/2xl3zlw51cb_wpkz99gc5pw80000gn/T//crystal-0.25.1-version.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   626    0   626    0     0   1301      0 --:--:-- --:--:-- --:--:--  1298
100 14.5M  100 14.5M    0     0  5216k      0  0:00:02  0:00:02 --:--:-- 8589k
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

Though then it still works, so I would consider this issue solved.

Not sure if this behaviour depend on curl version, my current curl:

```
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by imbsky** [comment]
It's already late at night in Japan today, so let me check early tomorrow morning. Thank you for checking!
