### ISSUE TITLE
[Feature request] Add list-legacy-filenames

### ISSUE THREAD

**Issue by mdwagner** [asdf-community/asdf-crystal#21]
Add   `bin/list-legacy-filenames` to include `.crystal-version` from crenv.

**Comment by imbsky** [comment]
@mdwagner I haven't tested but maybe the latest master will work for you. Please tell me if it doesn't work.

**Comment by imbsky** [comment]
By the way, thanks for reminding me about this!

**Comment by mdwagner** [comment]
@imbsky It works! Thank you!

**Comment by imbsky** [comment]
@mdwagner You're welcome!
